name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t markmdev/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true markmdev/react-test npm test

      - name: Build production versions of images
        run: |
          docker build -t markmdev/multi-client ./client
          docker build -t markmdev/multi-nginx ./nginx
          docker build -t markmdev/multi-server ./server
          docker build -t markmdev/multi-worker ./worker
